# Generated by Django 3.2.3 on 2021-05-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kanban', '0003_alter_card_due_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_day',
            field=models.DateTimeField(blank=True),
        ),
    ]
